use_frameworks!

##忽略.cocoapods中多个specs源引起的警告问题
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

platform :ios, '13.0'

target 'ZHHDraggableView_Example' do
  pod 'ZHHDraggableView', :path => '../'
  pod 'SnapKit'        # 自动布局 DSL
  # 调试工具（仅 Debug 下生效）
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']  # 自定义的服务器配置（仅在 Debug 模式下使用）

  target 'ZHHDraggableView_Tests' do
    inherit! :search_paths

    
  end
end
